### PR TITLE
fix(local): local conductor startup phrase parsing

### LINKED ISSUE #252: Flaky tests
Tryorama tests are currently flaky with the following error being produced for the failed tests

```bash
error occurred during test run: HolochainError [ConnectionError]: could not connect to Holochain Conductor API at ws://localh
ost:59225/ - AggregateError
    at WebSocket.<anonymous> (file:///private/tmp/forum/node_modules/.pnpm/@holochain+client@0.19.0-dev.6_bufferutil@4.0.8/no
de_modules/@holochain/client/lib/api/client.js:42:24)
    at callListener (/private/tmp/forum/node_modules/.pnpm/ws@8.18.0_bufferutil@4.0.8/node_modules/ws/lib/event-target.js:290
:14)
    at WebSocket.onError (/private/tmp/forum/node_modules/.pnpm/ws@8.18.0_bufferutil@4.0.8/node_modules/ws/lib/event-target.j
s:230:9)
    at WebSocket.emit (node:events:518:28)
    at emitErrorAndClose (/private/tmp/forum/node_modules/.pnpm/ws@8.18.0_bufferutil@4.0.8/node_modules/ws/lib/websocket.js:1
041:13)
    at ClientRequest.<anonymous> (/private/tmp/forum/node_modules/.pnpm/ws@8.18.0_bufferutil@4.0.8/node_modules/ws/lib/websoc
ket.js:881:5)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:101:11)
    at Socket.socketErrorListener (node:_http_client:504:5)
    at Socket.emit (node:events:518:28)

stdout | src/forum/posts/all-posts-entry-hash.test.ts > create a Post and get all posts entry hash
11:27:15 [Tryorama - Local Conductor] info: 2025-01-31T08:27:15.979921Z ERROR holochain::conductor::interface::websocket: cra
tes/holochain/src/conductor/interface/websocket.rs:200: error=Websocket closed: No connection
```

### Versions

- [0.18.0-dev.3](https://www.npmjs.com/package/@holochain/tryorama/v/0.18.0-dev.3)
- [0.17.0](https://www.npmjs.com/package/@holochain/tryorama/v/0.17.0)

### How to Reproduce

- Scaffold the forum example app with `hc-scaffold` (`0.4` or `0.5`) using 

```bash
hc scaffold example forum
cd forum
```
- Enter nix shell and install dependencies

```bash
nix develop
npm installl
``` 

- Run test suite; you will notice that the tests might fail or pass right away with the error above

```bash
npm test
```

### PR DESCRIPTION
**Pull request by jost-s**
resolves #252

### CODE REVIEW

File: ts/src/local/conductor.ts [hunk 1]
```diff
@@ -220,26 +220,17 @@ export class Conductor implements IConductor {
 
     const startPromise = new Promise<void>((resolve) => {
       runConductorProcess.stdout.on("data", (data: Buffer) => {
+        logger.info(data.toString());
         const conductorLaunched = data
           .toString()
           .match(/Conductor launched #!\d ({.*})/);
-        const holochainRunning = data
-          .toString()
-          .includes("Connected successfully to a running holochain");
```
Comment (ThetaSinner) [inline ts/src/local/conductor.ts:228]: Interesting, I think this is a sandbox line we were looking for. So some change in the sandbox caused this issue?

Looks like a good fix because it's simpler so yay. Just curious

Comment (jost-s) [reply ts/src/local/conductor.ts:228]: That code where the logs are output is 2 years old, so I think it's not a sandbox change. The thing is that usually when you look at the outputs of starting a sandbox, `Connected successfully to a running holochain" is output first, followed by `Conductor launched`. But in the code it's the other way around, `Conductor launched` is in fact the last line.

I don't know why this hasn't been creeping up earlier. Maybe no one paid attention to it too much?

On another note, this connected successfully log message makes no sense to me (anyone?), I'd like to remove it from the sandbox startup.

Comment (ThetaSinner) [reply ts/src/local/conductor.ts:228]: Oh this woke something in my memory. I moved those lines around in January, so this is my mistake I'm afraid. Yes that log line makes very little sense. It's really saying "We saved the lock file to remember which running conductors we have". We were logging that the conductor was ready to use before saving that lock file though which I thought was weird so I swapped the log lines.

I had no idea they were being read downstream.

Comment (ThetaSinner) [reply ts/src/local/conductor.ts:228]: https://github.com/holochain/holochain/pull/4587
